[package]
name = "many-migration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-error = { path = "../many-error", version = "0.1.0" }
minicbor = { version = "0.18.0", features = ["derive"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
strum = { version = "0.24", features = ["derive"] }
tracing = "0.1.37"

[dev-dependencies]
linkme = { version = "0.3.5", features = ["used_linker"] }
