[package]
name = "many-server"
version = "0.1.0"
edition = "2021"
description = "Library to build MANY modules and servers."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

[lib]
name = "many_server"

[dependencies]
anyhow = "1.0.44"
asn1 = { version = "0.11", default-features = false }
async-trait = "0.1.51"
backtrace = { version = "0.3", optional = true }
base32 = "0.4.0"
base64 = "0.13.0"
coset = "0.3"
crc-any = "2.4.0"
cryptoki = { version = "0.3", features = ["generate-bindings"] }
derive_builder = "0.10.2"
ecdsa = "0.12.4"
ed25519 = { version = "1.2.0", features = [ "std" ] }
ed25519-dalek = { version = "1.0.1", features = [ "std" ] }
fixed = "1.16.0"
hex = "0.4.3"
lazy_static = "1.4.0"
many-error = { path = "../many-error", version = "0.1.0" }
many-identity = { path = "../many-identity", version = "0.1.0", features = ["coset", "raw"] }
many-modules = { path = "../many-modules", version = "0.1.0" }
many-protocol = { path = "../many-protocol", version = "0.1.0" }
many-types = { path = "../many-types", version = "0.1.0" }
minicbor = { version = "0.18.0", features = ["derive", "half", "std"] }
num-bigint = "0.4.3"
num-derive = "0.3.3"
num-traits = "0.2.14"
once_cell = "1.10"
p256 = { version = "0.9.0", features = [ "pem", "ecdsa", "std" ] }
pem = { version = "1.0.0", optional = true }
pkcs8 = { version = "0.8", features = [ "pem", "std", "encryption" ] }
many-macros = { path = "../many-macros", version = "0.1.0" }
rand = "0.8.4"
regex = "1.5.4"
reqwest = { version = "0.11.5", features = ["blocking"] }
serde = { version = "1.0.130" }
serde_json = "1.0"
sha2 = "0.10"
sha3 = "0.9.1"
signature = "1.3"
static_assertions = "1.1.0"
strum = "0.24.0"
strum_macros = "0.24"
tracing = "0.1.29"
tokio = { version = "1.12.0", features = [ "full" ] }
tiny_http = "0.11.0"

[dev-dependencies]
many-identity = { path = "../many-identity", version = "0.1.0", features = ["coset", "raw", "testing"] }
proptest = "1.0.0"
semver = "1.0"
smol = "1.2.5"

[features]
default = []
client = []
raw = []
testing = []
# Whether to trace ManyError creation, which can be useful for debugging.
trace_error_creation = ["backtrace"]
