[package]
name = "many-server"
version = "0.1.0"
edition = "2021"
description = "Library to build MANY modules and servers."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

[lib]
name = "many_server"

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.51"
backtrace = { version = "0.3", optional = true }
base32 = "0.4.0"
base64 = "0.13.0"
coset = "0.3"
crc-any = "2.4.0"
derive_builder = "0.10.2"
fixed = "1.16.0"
hex = "0.4.3"
many-error = { path = "../many-error", version = "0.1.0" }
many-identity = { path = "../many-identity", version = "0.1.0", features = ["coset", "raw"] }
many-modules = { path = "../many-modules", version = "0.1.0" }
many-protocol = { path = "../many-protocol", version = "0.1.0" }
many-types = { path = "../many-types", version = "0.1.0" }
minicbor = { version = "0.18.0", features = ["derive", "half", "std"] }
num-bigint = "0.4.3"
num-derive = "0.3.3"
num-traits = "0.2.14"
once_cell = "1.10"
pem = { version = "1.0.0", optional = true }
many-macros = { path = "../many-macros", version = "0.1.0" }
regex = "1.5.4"
serde = { version = "1.0.130" }
sha3 = "0.9.1"
static_assertions = "1.1.0"
strum = "0.24.0"
strum_macros = "0.24"
tracing = "0.1.29"
tiny_http = "0.11.0"

[dev-dependencies]
many-server = { path = ".", features = ["testing"] }
many-identity = { path = "../many-identity", version = "0.1.0", features = ["coset", "raw", "testing"] }
many-identity-dsa = { path = "../many-identity-dsa", version = "0.1.0", features = ["ed25519", "testing"] }
proptest = "1.0.0"
semver = "1.0"
smol = "1.2.5"

[features]
default = []
client = []
raw = []
testing = []
# Whether to trace ManyError creation, which can be useful for debugging.
trace_error_creation = ["backtrace"]
