[package]
name = "many-types"
version = "0.1.0" # managed by release.sh
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-error = { path = "../many-error", version = "0.1.0" } # managed by release.sh
many-identity = { path = "../many-identity", version = "0.1.0" } # managed by release.sh
base64 = "0.20.0"
coset = "0.3.2"
derive_more = "0.99"
fixed = "1.16.0"
hex = "0.4.3"
minicbor = { version = "0.18.0", features = ["derive", "std", "half"] }
num-derive = "0.3.3"
num-traits = "0.2.14"
num-bigint = "0.4.3"
proptest = { version = "1.0.0", optional = true }
serde = "1.0.139"

[dev-dependencies]
cbor-diag = "0.1.11"
many-types = { path = ".", features = ["proptest"], version = "0.1.0" } # managed by release.sh
serde_test = "1.0.139"

[features]
cucumber = []
