[package]
name = "many-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-error = { path = "../many-error", version = "0.1.0" }
many-identity = { path = "../many-identity", version = "0.1.0" }
coset = "0.3.2"
fixed = "1.16.0"
hex = "0.4.3"
minicbor = { version = "0.18.0", features = ["derive", "std", "half"] }
num-derive = "0.3.3"
num-traits = "0.2.14"
num-bigint = "0.4.3"
proptest = { version = "1.0.0", optional = true }
serde = "1.0.139"

[dev-dependencies]
many-types = { path = ".", features = ["proptest"] }
serde_test = "1.0.139"
