[workspace]
members = [
    "src/many",
    "src/many-client",
    "src/many-error",
    "src/many-identity",
    "src/many-identity-cose",
    "src/many-identity-webauthn",
    "src/many-macros",
    "src/many-modules",
    "src/many-protocol",
    "src/many-server",
    "src/many-types",
]
