[package]
name = "many-modules"
version = "0.1.6" # managed by release.sh
edition = "2021"
description = "All modules declared in the specification."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-error = { path = "../many-error", version = "0.1.6" } # managed by release.sh
many-identity = { path = "../many-identity", version = "0.1.6" } # managed by release.sh
many-macros = { path = "../many-macros", version = "0.1.6" } # managed by release.sh
many-protocol = { path = "../many-protocol", version = "0.1.6" } # managed by release.sh
many-types = { path = "../many-types", version = "0.1.6" } # managed by release.sh
async-channel = "1.8.0"
async-trait = "0.1.68"
coset = "0.3.4"
derive_builder = "0.12.0"
hex = "0.4.3"
minicbor = { version = "0.19.1", features = ["derive"] }
num-bigint = "0.4.3"
num_enum = "0.6.1"
strum = "0.24.1"
strum_macros = "0.24.3"

[dev-dependencies]
cbor-diag = "0.1.12"
many-identity = { path = "../many-identity", features = ["raw", "testing"], version = "0.1.6" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = ["ed25519", "testing"], version = "0.1.6" } # managed by release.sh
mockall = "0.11.4"
once_cell = "1.17.1"
proptest = "1.2.0"
smol = "1.3.0"

[features]
cucumber = ["many-types/cucumber"]
