[package]
name = "many-modules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-error = { path = "../many-error", version = "0.1.0" }
many-identity = { path = "../many-identity", version = "0.1.0" }
many-macros = { path = "../many-macros", version = "0.1.0" }
many-protocol = { path = "../many-protocol", version = "0.1.0" }
many-types = { path = "../many-types", version = "0.1.0" }
async-trait = "0.1.56"
coset = "0.3.2"
derive_builder = "0.11.2"
hex = "0.4.3"
minicbor = { version = "0.18.0", features = ["derive"] }
num-bigint = "0.4.3"
num_enum = "0.5.7"
strum = "0.24.1"
strum_macros = "0.24.3"

[dev-dependencies]
cbor-diag = "0.1.11"
many-identity = { path = "../many-identity", version = "0.1.0", features = ["raw", "testing"] }
many-identity-dsa = { path = "../many-identity-dsa", version = "0.1.0", features = ["ed25519", "testing"] }
mockall = "0.11.1"
once_cell = "1.13.0"
proptest = "1.0.0"
smol = "1.2.5"

[features]
cucumber = ["many-types/cucumber"]
