[package]
name = "many-identity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
many-error = { path = "../many-error", version = "0.1.0" }
base32 = "0.4.0"
crc-any = "2.4.3"
coset = { version = "0.3.2", optional = true }
hex = "0.4.3"
minicbor = { version = "0.18.0", optional = true }
once_cell = "1.10"
serde = "1.0.139"
sha3 = "0.10.1"
static_assertions = "1.1.0"
tracing = "0.1.29"

[dev-dependencies]
many-identity = { path = ".", features = [ "serde", "testing" ] }
proptest = "1.0.0"
serde_test = "1.0.139"

[features]
default = ["coset", "minicbor"]
raw = []
serde = []
testing = []
