version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3
  rust: circleci/rust@1.6.0
  detect: circleci/os-detect@0.3.0

rust_cache_path: &rust_cache_path
  paths:
    - ~/.cargo
    - target/

executors:
  linux2004:
    machine:
      image: ubuntu-2004:current
  linux2204:
    machine:
      image: ubuntu-2204:current
  macos:
    macos:
      xcode: 13.4.1

jobs:
  lint:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-many-rs-build-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v1-many-rs-build-{{ arch }}-
      - rust/install:
          version: nightly
      - rust/format:
          nightly-toolchain: true
          with_cache: false
      - rust/clippy:
          flags: --all-targets --all-features -- -D clippy::all
          with_cache: false

  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-many-rs-build-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v1-many-rs-build-{{ arch }}-
      - rust/install:
          version: nightly
      - rust/build:
          crate: --all-features
          with_cache: false
      - save_cache:
          key: v1-many-rs-build-{{ arch }}-{{ checksum "Cargo.lock" }}
          <<: *rust_cache_path
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    environment:
      SOFTHSM2_CONF: /tmp/softhsm2.conf
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-many-rs-test-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v1-many-rs-test-{{ arch }}-
            - v1-many-rs-build-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v1-many-rs-build-{{ arch }}-
      - rust/install:
          version: nightly
      - when:
          condition:
            matches: { pattern: "^linux.*$", value: << parameters.os >> }
          steps:
            - rust/test:
                package: --lib --all-targets --all-features
                with_cache: false
      - when:
          condition:
            equal: [macos, << parameters.os >>]
          steps:
            - rust/test:
                package: --lib --all-targets --features default,client,raw,testing,trace_error_creation
                with_cache: false
      - when:
          condition:
            matches: { pattern: "^linux.*$", value: << parameters.os >> }
          steps:
            - rust/test:
                package: --all-features --doc
                with_cache: false
      - save_cache:
          key: v1-many-rs-test-{{ arch }}-{{ checksum "Cargo.lock" }}
          <<: *rust_cache_path
  coverage:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    environment:
      PKCS11_SOFTHSM2_MODULE: /usr/lib/softhsm/libsofthsm2.so
      SOFTHSM2_CONF: /tmp/softhsm2.conf
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-many-rs-coverage-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v1-many-rs-coverage-{{ arch }}-
            - v1-many-rs-test-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v1-many-rs-test-{{ arch }}-
            - v1-many-rs-build-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v1-many-rs-build-{{ arch }}-
      - rust/install:
          version: nightly
      - run:
          name: install llvm-tools-preview
          command: rustup component add llvm-tools-preview
      - run:
          name: install grcov
          command: cargo install grcov --root target/
      - run:
          name: generate test coverage
          command: cargo test --lib --all-targets --all-features
          environment:
            RUSTFLAGS: "-C instrument-coverage"
            LLVM_PROFILE_FILE: "coverage/lcov-%p-%m.profraw"
      - run:
          name: generate coverage report
          command: target/bin/grcov coverage --binary-path target/debug/ -s . --keep-only 'src/**' --prefix-dir $PWD -t lcov --branch --ignore-not-existing -o coverage/report.lcov
      - codecov/upload:
          file: coverage/report.lcov
      - save_cache:
          key: v1-many-rs-coverage-{{ arch }}-{{ checksum "Cargo.lock" }}
          <<: *rust_cache_path
  create:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - detect/init
      - rust/install:
          version: nightly
      - rust/build:
          release: true
          with_cache: false
      - run: mkdir -p artifacts
      - run:
          name: creating release archive
          command: file target/release/* | grep 'executable\|shared object' | cut -d ':' -f 1 | xargs tar czvf artifacts/many-rs_${CIRCLE_TAG}_${CIRCLE_SHA1}_${OSD_ID}_${OSD_VERSION}.tar.gz
      - run:
          name: creating release shasum
          command: shasum artifacts/many-rs_${CIRCLE_TAG}_${CIRCLE_SHA1}_${OSD_ID}_${OSD_VERSION}.tar.gz > artifacts/shasum_${CIRCLE_TAG}_${CIRCLE_SHA1}_${OSD_ID}_${OSD_VERSION}.txt
      - persist_to_workspace:
          root: artifacts
          paths:
            - "*.tar.gz"
            - "*.txt"
  publish:
    parameters:
      pre-release:
        type: boolean
        default: false
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/project/artifacts
      - when:
          condition:
            not: << parameters.pre-release >>
          steps:
            - run:
                name: publish pre-release
                command: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} ~/project/artifacts
      - when:
          condition: << parameters.pre-release >>
          steps:
            - run:
                name: publish pre-release
                command: ghr -prerelease -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} ~/project/artifacts
  audit:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-ghjobs-audit-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v1-ghjobs-audit-{{ arch }}-
      - run:
          name: install cargo-audit
          command: cargo install cargo-audit
      - run:
          name: cargo audit
          command: cargo audit
      - save_cache:
          key: v1-ghjobs-audit-{{ arch }}-{{ checksum "Cargo.lock" }}
          <<: *rust_cache_path

# Re-usable commands
commands:
  linux-dep:
    description: install linux dependencies
    parameters:
      os:
        type: string
    steps:
      - when:
          condition:
            matches: { pattern: "^linux.*$", value: << parameters.os >> }
          steps:
            - run:
                name: installing linux dependencies
                command: |
                  sudo apt -y update
                  sudo apt -y install build-essential pkg-config clang libssl-dev libsofthsm2
                  mkdir /tmp/tokens
                  echo "directories.tokendir = /tmp/tokens" > /tmp/softhsm2.conf
            - run:
                name: exporting linux environment variable
                command: |
                  echo 'export PKCS11_SOFTHSM2_MODULE=/usr/lib/softhsm/libsofthsm2.so' >> $BASH_ENV

  macos-dep:
    description: install macos dependencies
    parameters:
      os:
        type: string
    steps:
      - when:
          condition:
            equal: [macos, << parameters.os >>]
          steps:
            - run:
                name: installing macos dependencies
                command: |
                  brew install softhsm
                  mkdir /tmp/tokens
                  echo "directories.tokendir = /tmp/tokens" > /tmp/softhsm2.conf
            - run:
                name: exporting macos environment variable
                command: |
                  echo 'export PKCS11_SOFTHSM2_MODULE=/usr/local/lib/softhsm/libsofthsm2.so' >> $BASH_ENV
workflows:
  ci:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - lint:
          pre-steps:
            - linux-dep:
                os: << matrix.os >>
          name: lint-v<< matrix.os >>
          matrix:
            parameters:
              os: [linux2004]
      - build:
          pre-steps:
            - linux-dep:
                os: << matrix.os >>
            - macos-dep:
                os: << matrix.os >>
          name: build-v<< matrix.os >>
          matrix:
            parameters:
              os: [linux2004, macos]
      - test:
          pre-steps:
            - linux-dep:
                os: << matrix.os >>
            - macos-dep:
                os: << matrix.os >>
          name: test-v<< matrix.os >>
          matrix:
            parameters:
              os: [linux2004, macos]
          requires:
            - build-v<< matrix.os >>
      - coverage:
          pre-steps:
            - linux-dep:
                os: << matrix.os >>
            - macos-dep:
                os: << matrix.os >>
          name: coverage-v<< matrix.os >>
          matrix:
            parameters:
              os: [linux2004]
          requires:
            - test-v<< matrix.os >>
  release:
    when:
      not:
        equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
    jobs:
      - create:
          pre-steps:
            - linux-dep:
                os: << matrix.os >>
            - macos-dep:
                os: << matrix.os >>
          name: create-v<< matrix.os >>
          matrix:
            parameters:
              os: [linux2004, macos]
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
                - /^\d+\.\d+\.\d+-.*-rc.*$/
                - /^\d+\.\d+\.\d+-pre.*$/
      - publish:
          name: publish
          pre-release: false
          context:
            - GITHUB_CREDS
          requires:
            - create
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
      - publish:
          name: publish-pre-release
          pre-release: true
          context:
            - GITHUB_CREDS
          requires:
            - create
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+-.*-rc.*$/
                - /^\d+\.\d+\.\d+-pre.*$/
  security:
    when:
      and:
        - equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]
        - equal: [ "Audit", << pipeline.schedule.name >> ]
    jobs:
      - audit
