[package]
name = "many"
version = "0.1.0" # managed by release.sh
edition = "2021"
description = "CLI tool to communicate with the MANY protocol network."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

[[bin]]
name = "many"
path = "src/main.rs"

[dependencies]
many-cli-helpers = { path = "../many-cli-helpers" }
many-client = { path = "../many-client" }
many-error = { path = "../many-error" }
many-identity = { path = "../many-identity", features = ["coset"] }
many-identity-dsa = { path = "../many-identity-dsa", features = ["ecdsa", "ed25519"] }
many-identity-hsm = { path = "../many-identity-hsm" }
many-identity-webauthn = { path = "../many-identity-webauthn", features = ["identity"] }
many-mock = { path = "../many-mock" }
many-modules = { path = "../many-modules" }
many-protocol = { path = "../many-protocol" }
many-types = { path = "../many-types" }
many-server = { path = "../many-server" }
anyhow = "1.0.57"
async-recursion = "1.0"
atty = "0.2.14"
base64 = "0.13.0"
cbor-diag = "0.1.9"
clap = { version = "3.0.14", features = [ "derive" ] }
coset = "0.3"
hex = "0.4.3"
minicbor = { version = "0.18.0", features = ["derive", "half", "std"] }
rand = "0.8.5"
rpassword = "6.0"
tracing = "0.1.29"
tracing-subscriber = "0.3.15"
tokio = { version = "1.24.1", features = [ "full" ] }
url = "2.2.2"
