[package]
name = "many-identity-dsa"
version = "0.1.6" # managed by release.sh
edition = "2021"
description = "Digital Signature identity, verifiers and utility functions."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32 = "0.4.0"
crc-any = "2.4.3"
coset = { version = "0.3.4", optional = true }
ed25519 = { version = "2.2.2", features = [ "alloc", "std", "pem" ], optional = true }
ed25519-dalek = { version = "2", features = ["pkcs8", "rand_core"], optional = true }
many-error = { path = "../many-error", version = "0.1.6" } # managed by release.sh
many-identity = { path = "../many-identity", version = "0.1.6" } # managed by release.sh
minicbor = { version = "0.19.1", optional = true }
once_cell = "1.17.1"
p256 = { version = "0.13.2", features = [ "alloc", "pem", "ecdsa", "std" ] }
rand = { version = "0.8.5", optional = true }
serde = "=1.0.163"
sha2 = "0.10.6"
sha3 = "0.10.8"
tracing = "0.1.37"

[dev-dependencies]
proptest = "1.2.0"
many-protocol = { path = "../many-protocol", version = "0.1.6" } # managed by release.sh
many-identity-dsa = { path = ".", features = [ "default", "ecdsa", "ed25519", "serde", "testing" ], version = "0.1.6" } # managed by release.sh
serde_test = "1.0.163"

[features]
default = ["coset", "minicbor"]
ecdsa = []
ed25519 = ["dep:ed25519", "dep:ed25519-dalek"]
raw = []
serde = []
testing = ["dep:rand"]
