[package]
name = "many-identity-dsa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asn1 = { version = "0.8", default-features = false }
base32 = "0.4.0"
crc-any = "2.4.3"
cryptoki = { version = "0.3", features = ["generate-bindings"] }
coset = { version = "0.3.2", optional = true }
ed25519 = { version = "1.2.0", features = [ "std" ], optional = true }
ed25519-dalek = { version = "1.0.1", optional = true }
hex = "0.4.3"
many-error = { path = "../many-error", version = "0.1.0" }
many-identity = { path = "../many-identity", version = "0.1.0" }
minicbor = { version = "0.18.0", optional = true }
once_cell = "1.10"
p256 = { version = "0.9.0", features = [ "pem", "ecdsa", "std" ] }
pkcs8 = { version = "0.8", features = [ "pem", "std", "encryption" ] }
rand = { version = "0.8" }
rand_07 = { package = "rand", version = "0.7", optional = true }  # Version compatible with ed25519-dalek
serde = "1.0.139"
sha2 = "0.10.2"
sha3 = "0.10.1"
signature = "1.3"
tracing = "0.1.29"

[dev-dependencies]
proptest = "1.0.0"
many-protocol = { path = "../many-protocol", version = "0.1.0" }
many-identity-dsa = { path = ".", features = [ "default", "ecdsa", "ed25519", "serde", "testing" ] }
serde_test = "1.0.139"

[features]
default = ["coset", "minicbor"]
ecdsa = []
ed25519 = ["dep:ed25519", "dep:ed25519-dalek"]
raw = []
serde = []
testing = ["dep:rand_07"]
