[package]
name = "many-identity-dsa"
version = "0.1.1" # managed by release.sh
edition = "2021"
description = "Digital Signature identity, verifiers and utility functions."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base32 = "0.4.0"
crc-any = "2.4.3"
coset = { version = "0.3.2", optional = true }
ed25519 = { version = "2.1.0", features = [ "alloc", "std", "pem" ], optional = true }
ed25519-dalek = { version = "1.0.1", optional = true }
many-error = { path = "../many-error", version = "0.1.1" } # managed by release.sh
many-identity = { path = "../many-identity", version = "0.1.1" } # managed by release.sh
minicbor = { version = "0.19.1", optional = true }
once_cell = "1.10"
p256 = { version = "0.13.0", features = [ "alloc", "pem", "ecdsa", "std" ] }
rand = { version = "0.8", optional = true }
rand_07 = { package = "rand", version = "0.7", optional = true }  # Version compatible with ed25519-dalek
serde = "1.0.139"
sha2 = "0.10.2"
sha3 = "0.10.6"
tracing = "0.1.29"

[dev-dependencies]
proptest = "1.0.0"
many-protocol = { path = "../many-protocol", version = "0.1.1" } # managed by release.sh
many-identity-dsa = { path = ".", features = [ "default", "ecdsa", "ed25519", "serde", "testing" ], version = "0.1.1" } # managed by release.sh
serde_test = "1.0.139"

[features]
default = ["coset", "minicbor"]
ecdsa = []
ed25519 = ["dep:ed25519", "dep:ed25519-dalek"]
raw = []
serde = []
testing = ["dep:rand", "dep:rand_07"]
