[package]
name = "many-identity-webauthn"
version = "0.1.7" # managed by release.sh
edition = "2021"
description = "Verifiers for WebAuthn signed envelopes."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
authenticator-ctap2-2021 = { version = "0.3.2-dev.1", optional = true, default-features = false, features = ["crypto_openssl"] }
base64 = "0.21.2"
base64urlsafedata = { version = "0.1.3", optional = true }
coset = "0.3.4"
many-error = { path = "../many-error", version = "0.1.7" } # managed by release.sh
many-identity = { path = "../many-identity", version = "0.1.7" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = ["ecdsa"], version = "0.1.7" } # managed by release.sh
many-modules = { path = "../many-modules", optional = true, version = "0.1.7" } # managed by release.sh
many-protocol = { path = "../many-protocol", version = "0.1.7" } # managed by release.sh
many-types = { path = "../many-types", version = "0.1.7" } # managed by release.sh
minicbor = "0.19.1"
once_cell = "1.17.1"
rand = { version = "0.8.5", optional = true }
rpassword = { version = "7.2.0", optional = true }
serde = "=1.0.163"
serde_cbor = { version = "0.11.2", optional = true }
serde_json = "1.0.96"
sha2 = "0.10.6"
tracing = "0.1.37"
webauthn-authenticator-rs = { version = "0.4.9", optional = true, features = ["u2fhid", "usb"] }
webauthn-rs = { version = "0.4.8", optional = true }
webauthn-rs-proto = { version = "0.4.9", optional = true }

[dev-dependencies]
hex = "0.4.3"

[features]
default = ["identity"]
identity = [
    "dep:authenticator-ctap2-2021",
    "dep:base64urlsafedata",
    "dep:many-modules",
    "dep:rand",
    "dep:rpassword",
    "dep:serde_cbor",
    "dep:webauthn-authenticator-rs",
    "dep:webauthn-rs",
    "dep:webauthn-rs-proto",
]
