[package]
name = "many-ledger-test-utils"
version = "0.1.2-rc.2" # managed by release.sh
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
homepage = "https://liftedinit.org"
repository = "https://github.com/liftedinit/many-framework"
publish = false

[dependencies]
async-channel = "1.8"
coset = "0.3"
cucumber = { version = "0.19.1", features = ["libtest"] }
itertools = "0.10.3"
many-error = { path = "../../many-error", version = "0.1.2-rc.2" } # managed by release.sh
many-identity = { path = "../../many-identity", features = ["default", "serde", "testing"], version = "0.1.2-rc.2" } # managed by release.sh
many-identity-dsa = { path = "../../many-identity-dsa", features = ["ed25519", "ecdsa", "testing"], version = "0.1.2-rc.2" } # managed by release.sh
many-ledger = { path = "..", features = ["balance_testing"], version = "0.1.2-rc.2" } # managed by release.sh
many-migration = { path = "../../many-migration", version = "0.1.2-rc.2" } # managed by release.sh
many-modules = { path = "../../many-modules", features = ["cucumber"], version = "0.1.2-rc.2" } # managed by release.sh
many-protocol = { path = "../../many-protocol", version = "0.1.2-rc.2" } # managed by release.sh
many-types = { path = "../../many-types", features = ["cucumber"], version = "0.1.2-rc.2" } # managed by release.sh
merk = { git = "https://github.com/liftedinit/merk.git", rev = "857bf81963d9282ab03438da5013e1f816bd9da1" }
minicbor = { version = "0.19.1", features = ["derive", "std"] }
once_cell = "1.12"
proptest = "1"
serde_json = "1.0.72"
tempfile = "3.3.0"
tracing = "0.1.28"
