[package]
name = "many-ledger-test-macros"
version = "0.1.4" # managed by release.sh
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
homepage = "https://liftedinit.org"
repository = "https://github.com/liftedinit/many-framework"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.28"
syn = "2.0.17"
