[package]
name = "many-kvstore"
version = "0.1.0"
edition = "2021"
authors = ["The Lifted Initiative"]
license = "Apache-2.0"
description = ""
readme = "README.md"
homepage = "https://liftedinit.org"
repository = "https://github.com/liftedinit/many-framework"
keywords = ["cli", "web3", "blockchain", "tendermint", "proto", "crypto", "liftedinit"]
categories = ["command-line-utilities"]
build = "build.rs"

[[bin]]
name = "many-kvstore"
doc = false

[dependencies]
async-trait = "0.1.51"
clap = { version = "3.0.0", features = ["derive"] }
coset = "0.3"
merk = { git = "https://github.com/liftedinit/merk.git", rev = "857bf81963d9282ab03438da5013e1f816bd9da1" }
hex = { version = "0.4.3", features = ["serde"] }
json5 = "0.4.1"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
minicbor = { version = "0.18.0", features = ["derive", "std"] }
many-cli-helpers = { path = "../many-cli-helpers", version = "0.1.0" }
many-error = { path = "../many-error", version = "0.1.0" }
many-identity = { path = "../many-identity", version = "0.1.0", features = ["default", "serde"] }
many-identity-dsa = { path = "../many-identity-dsa", version = "0.1.0", features = ["ed25519", "ecdsa"]  }
many-modules = { path = "../many-modules", version = "0.1.0" }
many-protocol = { path = "../many-protocol", version = "0.1.0" }
many-server = { path = "../many-server", version = "0.1.0" }
many-types = { path = "../many-types", version = "0.1.0" }
serde = "1.0.130"
sha3 = "0.10.4"
signal-hook = "0.3.13"
strum = "0.24.1"
tokio = { version = "1.24.1", features = [ "full" ] }
tracing = "0.1.28"

[dev-dependencies]
async-channel = "1.8"
once_cell = "1.14.0"
many-identity = { path = "../many-identity", version = "0.1.0", features = ["default", "serde", "testing"] }
many-identity-dsa = { path = "../many-identity-dsa", version = "0.1.0", features = [ "ed25519", "testing" ] }
tempfile = "3.3.0"

[build-dependencies]
vergen = "7"

