[package]
name = "many-ledger"
version = "0.1.6" # managed by release.sh
edition = "2021"
description = "MANY ledger server."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]
build = "build.rs"

[[bin]]
name = "many-ledger"
doc = false

[dependencies]
async-channel = "1.8.0"
async-trait = "0.1.68"
base64 = "0.21.2"
bip39-dict = "0.1.1"
clap = { version = "3.2.25", features = ["derive"] }
coset = "0.3.4"
const_format = "0.2.30"
fixed = "1.23.1"
merk = { git = "https://github.com/liftedinit/merk.git", rev = "857bf81963d9282ab03438da5013e1f816bd9da1" }
hex = "0.4.3"
itertools = "0.10.5"
json5 = "0.4.1"
linkme = { version = "0.3.9", features = ["used_linker"] }
num-bigint = "0.4.3"
num-traits = "0.2.15"
minicbor = { version = "0.19.1", features = ["derive", "std"] }
many-cli-helpers = { path = "../many-cli-helpers", version = "0.1.6" } # managed by release.sh
many-error = { path = "../many-error", version = "0.1.6" } # managed by release.sh
many-identity = { path = "../many-identity", features = ["default", "serde"], version = "0.1.6" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = ["ed25519", "ecdsa"] , version = "0.1.6" } # managed by release.sh
many-identity-webauthn = { path = "../many-identity-webauthn", version = "0.1.6" } # managed by release.sh
many-migration = { path = "../many-migration", version = "0.1.6" } # managed by release.sh
many-modules = { path = "../many-modules", version = "0.1.6" } # managed by release.sh
many-protocol = { path = "../many-protocol", version = "0.1.6" } # managed by release.sh
many-server = { path = "../many-server", version = "0.1.6" } # managed by release.sh
many-server-cache = { path = "../many-server-cache", version = "0.1.6" } # managed by release.sh
many-types = { path = "../many-types", version = "0.1.6" } # managed by release.sh
rand = "0.8.5"
serde = "=1.0.163"
serde_json = "1.0.96"
sha3 = "0.10.8"
signal-hook = "0.3.15"
strum = "0.24.1"
tokio = { version = "1.28.1", features = [ "full" ] }
tracing = "0.1.37"
typenum = "1.16.0"

[dev-dependencies]
cucumber = { version = "0.19.1", features = ["libtest"] }
once_cell = "1.17.1"
many-identity = { path = "../many-identity", features = ["default", "serde", "testing"], version = "0.1.6" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = [ "ed25519", "testing" ], version = "0.1.6" } # managed by release.sh
many-ledger = { path = ".", features = ["balance_testing", "migration_testing"] }
many-modules = { path = "../many-modules", features = ["cucumber"], version = "0.1.6" } # managed by release.sh
many-types = { path = "../many-types", features = ["cucumber"], version = "0.1.6" } # managed by release.sh
proptest = "1.2.0"
tempfile = "3.5.0"
tokio = "1.28.1"
many-ledger-test-utils = { path = "test-utils", version = "0.1.6" } # managed by release.sh
many-ledger-test-macros = { path = "test-macros", version = "0.1.6" } # managed by release.sh

[[test]]
name = "create_token"
path = "tests/ledger_tokens/create_token.rs"
harness = false

[[test]]
name = "update_token"
path = "tests/ledger_tokens/update_token.rs"
harness = false

[[test]]
name = "add_token_ext_info"
path = "tests/ledger_tokens/add_token_ext_info.rs"
harness = false

[[test]]
name = "remove_token_ext_info"
path = "tests/ledger_tokens/remove_token_ext_info.rs"
harness = false

[build-dependencies]
vergen = { version = "8.2.1", features = ["git", "git2"] }

[features]
balance_testing=[]                  # Enable balance initialization from the CLI
migration_testing=[]                # Enable Dummy migration
webauthn_testing=[]                 # Disable WebAuthn token validation from the CLI
