[package]
name = "many-mock"
version = "0.1.2-rc.1" # managed by release.sh
edition = "2021"
description = "Utility types for creating mocked MANY servers."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
coset = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.3"
regex = "1.5.4"
many-error = { path = "../many-error", version = "0.1.2-rc.1" } # managed by release.sh
many-identity = { path = "../many-identity", version = "0.1.2-rc.1" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = ["ed25519"], version = "0.1.2-rc.1" } # managed by release.sh
many-identity-webauthn = { path = "../many-identity-webauthn", version = "0.1.2-rc.1" } # managed by release.sh
many-modules = { path = "../many-modules", version = "0.1.2-rc.1" } # managed by release.sh
many-protocol = { path = "../many-protocol", version = "0.1.2-rc.1" } # managed by release.sh
many-server = { path = "../many-server", version = "0.1.2-rc.1" } # managed by release.sh
cbor-diag = "0.1"

[dev-dependencies]
cucumber = { version = "0.19.1", features = ["libtest"] }
futures = "0.3"
many-client = { path = "../many-client", version = "0.1.2-rc.1" } # managed by release.sh
serde_json = "1.0"
ciborium = "0.2"
tokio = "1.24.1"

[[test]]
name = "integration"
harness = false
