[package]
name = "many-mock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
coset = "0.3"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
regex = "1.5.4"
many-error = { path = "../many-error", version = "0.1.0" }
many-identity = { path = "../many-identity", version = "0.1.0" }
many-identity-dsa = { path = "../many-identity-dsa", version = "0.1.0", features = ["ed25519"] }
many-identity-webauthn = { path = "../many-identity-webauthn", version = "0.1.0" }
many-modules = { path = "../many-modules", version = "0.1.0" }
many-protocol = { path = "../many-protocol", version = "0.1.0" }
many-server = { path = "../many-server", version = "0.1.0" }
cbor-diag = "0.1"

[dev-dependencies]
cucumber = "0.13"
futures = "0.3"
many-client = { path = "../many-client", version = "0.1.0" }
serde_json = "1.0"
ciborium = "0.2"
tokio = "1.24.1"

[[test]]
name = "integration"
harness = false
