[package]
name = "many-identity-hsm"
version = "0.1.4" # managed by release.sh
edition = "2021"
description = "Hardware Security Module based identity, verifiers and utility functions."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asn1 = "0.15.2"
coset = "0.3.4"
cryptoki = { version = "0.3.1", features = ["generate-bindings"] }
hex = "0.4.3"
many-error = { path = "../many-error", version = "0.1.4" } # managed by release.sh
many-identity = { path = "../many-identity", version = "0.1.4" } # managed by release.sh
many-identity-dsa = { path = "../many-identity-dsa", features = ["ecdsa"], version = "0.1.4" } # managed by release.sh
once_cell = "1.17.1"
p256 = "0.13.2"
sha2 = "0.10.6"
tracing = "0.1.37"
