[package]
name = "many-client"
version = "0.1.0"
edition = "2021"
description = "Client library to communicate with the MANY protocol network."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.51"
base32 = "0.4.0"
base64 = "0.13.0"
coset = "0.3"
crc-any = "2.4.0"
derive_builder = "0.10.2"
ecdsa = "0.16.0"
ed25519 = { version = "1.2.0", features = [ "std" ] }
ed25519-dalek = { version = "1.0.1", features = [ "std" ] }
fixed = "1.16.0"
hex = "0.4.3"
many-client-macros = { path = "../many-client-macros", version = "0.1.0" }
many-identity = { path = "../many-identity", version = "0.1.0" }
many-identity-dsa = { path = "../many-identity-dsa", version = "0.1.0" }
many-modules = { path = "../many-modules", version = "0.1.0" }
many-protocol = { path = "../many-protocol", version = "0.1.0" }
many-types = { path = "../many-types", version = "0.1.0" }
minicbor = { version = "0.18.0", features = ["derive", "half", "std"] }
num-derive = "0.3.3"
num-traits = "0.2.14"
num-bigint = "0.4.3"
p256 = { version = "0.13.0", features = [ "pem", "ecdsa", "std" ] }
pem = { version = "1.0.0", optional = true }
many-server = { path = "../many-server", version = "0.1.0" }
rand = "0.8.4"
regex = "1.5.4"
reqwest = { version = "0.11.5", features = ["blocking"] }
serde = { version = "1.0.130" }
sha3 = "0.9.1"
static_assertions = "1.1.0"
tracing = "0.1.29"
tokio = { version = "1.24.1", features = [ "full" ] }
tiny_http = "0.11.0"

[features]
default = []
client = []
