[package]
name = "many-macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros to support create MANY modules."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

[lib]
proc-macro = true

[dependencies]
inflections = "1.1.1"
proc-macro2 = "1.0.36"
quote = "1.0.14"
serde = "1.0.134"
serde_tokenstream = "0.1.3"
syn = "1.0.86"

