[package]
name = "many-macros"
version = "0.1.2-rc.1" # managed by release.sh
edition = "2021"
description = "Procedural macros to support create MANY modules."
license-file = "../../LICENSE"
homepage = "https://liftedinit.org/"
repository = "https://github.com/liftedinit/many-rs.git"
authors = ["The Lifted Initiative <crates@liftedinit.org>"]

[lib]
proc-macro = true

[dependencies]
inflections = "1.1.1"
proc-macro2 = "1.0.54"
quote = "1.0.26"
serde = "1.0.134"
serde_tokenstream = "0.2.0"
syn = "2.0.12"

