[package]
name = "many-error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minicbor = { version = "0.18.0", optional = true, features = ["alloc"] }
num-derive = "0.3.3"
num-traits = "0.2.14"
regex = "1.6.0"

[features]
default = ["minicbor"]
